
server:
  port: 8080

spring:
    datasource:
      username: root
      password: admin123
      url: jdbc:mysql://localhost:3306/db_mi?useUnicode=true&characterEncoding=utf-8
      driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
    type-aliases-package: com.gyz.db.pojo
    mapper-locations:
      - classpath:mybatis/mapper/*.xml
