# application.yml文件中添加如下配置：
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_mi?useUnicode=true&characterEncoding=utf-8
    username: root
    password: admin123
    driver-class-name: com.mysql.jdbc.Driver